# model_hyperparameters.yaml
model:
  dataset: CARLA object detection
  name: YOLO_NAS_nano
  hyperparameters:
    optimizer:
      type: AdamW
      learning_rate: 0.0001
      weight_decay: 0.0001
    loss: crossentropy
    metrics:
      - accuracy
      - top_k_categorical_accuracy

training:
  use_wandb: False
  batch_size: 12
  epochs: 1000
  save_path: "checkpoint/custom"
  early_stopping:
    monitor: val_loss
    patience: 50

data:
  train_dir: "data/carla_data/train"
  val_dir: "data/carla_data/val"
  test_dir: "data/carla_data/test"
  train_annotation: "data/carla_data/train/train_annotations.json"
  val_annotation: "data/carla_data/val/val_annotations.json"
  test_annotation: "data/carla_data/test/test_annotations.json"
  augmentation:
    resize: 512
    normalize: true
